### ISSUE TITLE
Couldn't find a result file

### ISSUE THREAD

**Issue by xiaoyaogaobin** [inlife/nexrender#820] opened 2023-01-01 08:16 UTC
C:\phpstudy_pro\nest>nexrender-cli-win64.exe --file main.json --binary="C:/Program Files/Adobe/Adobe After Effects CC/Support Files/aerender.exe"
> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[P5MXNVmgPSA5flXzb53ys] setting up job...
[P5MXNVmgPSA5flXzb53ys] working directory is: C:\Users\Administrator\AppData\Local\Temp\nexrender\P5MXNVmgPSA5flXzb53ys
[P5MXNVmgPSA5flXzb53ys] applying predownload actions...
[P5MXNVmgPSA5flXzb53ys] downloading assets...
[P5MXNVmgPSA5flXzb53ys] applying postdownload actions...
[P5MXNVmgPSA5flXzb53ys] applying prerender actions...
[P5MXNVmgPSA5flXzb53ys] running script assemble...
[P5MXNVmgPSA5flXzb53ys] rendering job...
[P5MXNVmgPSA5flXzb53ys] rendering reached an error: After Effects�: �c�S
[P5MXNVmgPSA5flXzb53ys] rendering took ~12.037 sec.
[P5MXNVmgPSA5flXzb53ys] writing aerender job log to: C:\Users\Administrator\AppData\Local\Temp\nexrender\aerender-P5MXNVmgPSA5flXzb53ys.log
[P5MXNVmgPSA5flXzb53ys] dumping aerender log:
aerender version Using DXGI: Device: "NVIDIA GeForce GTX 1650" has dedicated video RAM (MB): 3962
Qt: Untested Windows version 6.2 detected!
12.0x404
aerender Error: After Effects�: �c�S
[undefined] cleaning up...
> job rendering failed
Error: Couldn't find a result file: C:\Users\Administrator\AppData\Local\Temp\nexrender\P5MXNVmgPSA5flXzb53ys\result.avi
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\render.js)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[undefined] Temporary AfterEffects project deleted. If you want to inspect it for debugging, use "--skip-cleanup"

C:\phpstudy_pro\nest>

**Comment by limzykenneth** [comment] 2023-01-01 16:38
Same with the other issue you opened, just posting the error log isn't quite enough for us to diagnose the problem.

**Comment by xiaoyaogaobin** [comment] 2023-01-02 01:11
main.json：

{
  "template": {
    "src": "https://h5cdn.xiaobaoshiguang.com/static/two.aep",
    "composition": "main"
  },
  "actions":{
    "postrender": [
      {
        "module": "@nexrender/action-encode",
        "preset": "mp4",
        "output": "encoded.mp4",
        "params": {"-vcodec": "libx264", "-r": 25}
      },
      {
        "module": "@nexrender/action-copy",
        "input": "encoded.mp4",
        "output": "C:/phpstudy_pro/nest/myresult.mp4"
      }
    ]
  }
}

**Comment by xiaoyaogaobin** [comment] 2023-01-02 01:12
IMAGE

**Comment by xiaoyaogaobin** [comment] 2023-01-02 01:15
https://h5cdn.xiaobaoshiguang.com/static/1672621869727.jpg
https://h5cdn.xiaobaoshiguang.com/static/1672621624539.jpg
image problem

**Comment by douglasprod** [comment] 2023-01-02 19:50
Try add paremeter `--skip-cleanup` when you start nexrender client. When it failed again, go to the job temp folder and make screen this folder and send log file. I need some more information for help you
![image](https://user-images.githubusercontent.com/36680471/210273305-5bfaf5ee-44e9-417f-80e0-428089f90ced.png)

**Comment by xiaoyaogaobin** [comment] 2023-01-02 23:06
Using DXGI: Device: "NVIDIA GeForce GTX 1650" has dedicated video RAM (MB): 3962
Qt: Untested Windows version 6.2 detected!
aerender version 12.0x404
aerender Error: After Effects�: �c�S

**Comment by limzykenneth** [comment] 2023-01-04 15:24
@xiaoyaogaobin Is that the full output from the log file?

**Comment by JamesBotterill** [comment] 2023-01-12 21:14
I believe this is linked to an issue I've found in the nexrender-worker-macos binary too.

The root cause of this is I'm using AE 2023 so the default output is a result.mp4 not result.mov which is the error I'm receiving.

**_Couldn't find a result file: /var/folders/b5/7nxzzk591fscsbr4wbw0tmk00000gp/T/nexrender/AjPiNa7VxaI7afCPsYyK0/result.mov._**

As it's a binary I'm unable to confirm that the most recent updates to the render.js in nexrender-core is validating the file type as it should be.

**Comment by limzykenneth** [comment] 2023-01-13 13:10
@JamesBotterill AE2023 outputting mp4 should be [covered by](https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/tasks/render.js#L213) the renderer core since 2 months ago, I'm not sure if the binary are updated between then and now though.

**Comment by JamesBotterill** [comment] 2023-01-13 13:51
@limzykenneth yes I have tested using npm install alongside the binary and the issue still occurs.

From investigation the issue looks to be in the render.js within nexrender-core, the outputExt: mp4 is forcing the filename to be correct as part of setup and avoiding this check within the render.js file.

`          const movOutputFile = outputFile.replace(/\.avi$/g, '.mov')
            const existsMovOutputFile = fs.existsSync(movOutputFile)
            if (existsMovOutputFile) {
              job.output = movOutputFile
            } else {
                // AE 2023 use mp4 output files
                const mp4OutputFile = outputFile.replace(/\.avi$/g, '.mp4')
                const existsMp4OutputFile = fs.existsSync(mp4OutputFile)
                if (existsMp4OutputFile) {
                    job.output = mp4OutputFile
                }
            }
` 

I've not been able to perform any deeper analysis as of yet

**Comment by JamesBotterill** [comment] 2023-01-13 21:17
I've submitted the following pull request to fix the issue I found 

https://github.com/inlife/nexrender/pull/831

@xiaoyaogaobin you might want to look at this to see if it also resolves your issue.

**Comment by DigitalTwelfthMan** [comment] 2023-01-23 12:04
This should be fixed in the most recent version, can you confirm

**Closed** 2023-04-01 12:37 UTC
Labels: type:bug, wontfix

**Comment by inlife** [comment] 2023-05-11 07:05
Additionally, for a similar issue, there is a recommendation for AE2023 added to the readme: https://github.com/inlife/nexrender#after-effects-2023
