### ISSUE TITLE
FIFO features Is not working properly in Nexrender server 

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#492] opened 2020-10-15 12:05 UTC
The nexrender server is allocating tasks to workers in unordered way. I allocated 30 jobs to 4 workers. A lot of times the latest/new jobs are getting fetched by workers first even when there are older jobs that are still in queue.
I have used your FIFO features for setting the ordered by still , it is not working properly and fetch new job priority basis then old JOB , Please help me out for it

**Comment by inlife** [comment] 2020-10-17 08:41
Hey @pixelfactorydevelopmentteam 

I found the cause of the issue, since new entries added to the end of the array, the order of fifo was actually swapped, it rather was a lifo
I pushed a commit that should fix that

**Comment by pixelfactorydevelopmentteam** [comment] 2020-11-06 06:21
Hi Team , 

I have checked your repository which is show that you have pushed 5 days ago so may I know that have  you fix the issue related to the lifo on this build?

**Comment by inlife** [comment] 2020-11-07 09:00
Hey @pixelfactorydevelopmentteam 

The issue with FIFO should be fixed in the build 21 days ago, and all builds later on.

**Comment by pixelfactorydevelopmentteam** [comment] 2020-11-09 04:00
Ok Let me check it

**Closed** 2021-03-16 08:32 UTC
Labels: type:bug, wontfix
