### ISSUE TITLE
aerender ERROR An existing connection was forcibly closed by the remote host [Not Sure what I am doing wrong]

### ISSUE THREAD

**Issue by adiwithadidas** [inlife/nexrender#314] opened 2020-02-12 10:34 UTC
Describe your question, attach logs, images or anything that might help to better understand it.
Hi,
I am getting this error when running nexrender-cli --file myjob.json  . I am using JSX file to alter the AEP file. I had run the JSX file in Extended Script toolkit and it runs without any error, But when I run it through the JSON file of Nexrender I get the error .

`
C:\Users\Hp\Desktop\testing_things>nexrender-cli --file main2.json
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[_LFrGE33_Sg3P7tnu39GV] setting up job...
[_LFrGE33_Sg3P7tnu39GV] working directory is: C:\Users\Hp\AppData\Local\Temp\nexrender\_LFrGE33_Sg3P7tnu39GV
[_LFrGE33_Sg3P7tnu39GV] downloading assets...
[_LFrGE33_Sg3P7tnu39GV] applying prerender actions...
[_LFrGE33_Sg3P7tnu39GV] running script assemble...
[_LFrGE33_Sg3P7tnu39GV] rendering job...
[_LFrGE33_Sg3P7tnu39GV] rendering took ~86.669 sec.
[_LFrGE33_Sg3P7tnu39GV] writing aerender job log to: C:\Users\Hp\AppData\Local\Temp\nexrender\aerender-_LFrGE33_Sg3P7tnu39GV.log
[_LFrGE33_Sg3P7tnu39GV] dumping aerender log:
aerender version 16.1.1x4
Using DXGI: Device: "Intel(R) HD Graphics 520" has dedicated video RAM (MB): 128 and has shared video RAM (MB): 4041 (Total: 4169 MB)
Unable to read VR Path Registry from C:\Users\Hp\AppData\Local\openvr\openvrpaths.vrpath
Running Script: C:\Users\Hp\AppData\Local\Temp\nexrender\_LFrGE33_Sg3P7tnu39GV\nexrender-_LFrGE33_Sg3P7tnu39GV-script.jsx
aerender ERROR An existing connection was forcibly closed by the remote host.
: Unable to receive at line 316
aerender ERROR: After Effects can not render for aerender. Another instance of aerender, or another script, may be running; or, AE may be waiting for response from a modal dialog, or for a render to complete. Try running aerender without the -reuse flag to invoke a separate instance of After Effects

> job rendering failed
Error: Couldn't find a result file
    at ChildProcess.<anonymous> (C:\Users\Hp\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:137:31)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
`

![Capture](https://user-images.githubusercontent.com/3817327/74327272-dcf7d100-4db1-11ea-8789-1c233a35227a.PNG)

I am not sure, what I am doing wrong. I searched a lot in Google and also in the issues section but couldn't find any relevant solution.

Can you please help me out on this. Any help would be deeply appreciated.

Thanks & Regards
Adi

**Comment by inlife** [comment] 2020-02-12 10:43
Try to check if you have any other after effect instances running in the background via process monitor

**Comment by inlife** [comment] 2020-02-12 10:46
Also please try to provide as much information about your system and your setup as possible, like which OS version are you using, which After Effects version, etc.

**Comment by adiwithadidas** [comment] 2020-02-12 10:56
I did checked the Background Process and there was no After effects process running 

I am using Nexrender CLI version
OS: Windows 10 
After Effect version 2019
No I am not using any custom 3rd Party plugin in it. 

JSON File I am using : https://miscellaneousfolder.s3-us-west-2.amazonaws.com/nexrender/main2.json
JSX FIle I am using :  https://miscellaneousfolder.s3-us-west-2.amazonaws.com/nexrender/aep+file+generate2.jsx


Please let me know if there is any thing I can do to fix this

Thanks

**Comment by inlife** [comment] 2020-02-12 14:01
does the issue still occur without your custom scripting file?

**Comment by adiwithadidas** [comment] 2020-02-12 15:15
Nope, Without the custom scripting file its working fine.

**Comment by inlife** [comment] 2020-02-12 15:16
Oh, I see, so maybe the issue is related to your script?
Have you tried removing portions of the script to see if that helps?

**Comment by adiwithadidas** [comment] 2020-02-12 15:18
I also doubt that, But the script is working fine without any error when I run it in Extended Script toolkit with After Effect.
So, I guess the script file is fine, but don't know why it's giving me the error when I run it through Nexrender.

**Comment by inlife** [comment] 2020-02-12 15:21
I feel like the issues might be related to the file operations that are happening in the script.

**Comment by adiwithadidas** [comment] 2020-02-12 15:23
Yeah might be, Let me try with some simple operations in the script and see if that works. I will get back to you about my findings.

Thanks

**Comment by AstroTom** [comment] 2020-02-20 09:23
I am having the same problem. My script works fine when run inside After Effect, but fails with the same message inside nexrender. I am running on Windows 2016.

From searching around it seems that the Adobe error message "aerender ERROR An existing connection was forcibly closed by the remote host." does not necessarily mean what it says, but is a generic After Effect error. There are limitations/ bugs in aerender.exe that returns errors in the same cases when the GUI does *not* return errors. 

See for example- https://community.adobe.com/t5/after-effects/after-effects-aerender-issues/td-p/10136595?page=1

**Closed** 2020-06-23 14:01 UTC
Labels: type:question
